### ISSUE TITLE
cannot connect to mongodb hosted on mlab.com

### ISSUE THREAD

**Issue by Pechi77** [rianrajagede/flask-mongodb#2]
how to connect to mlab.com

**Comment by rianrajagede** [comment]
@Pechi77 have you set your mongodb host? adjust your mongodb host in `run.py` :

```
client = MongoClient('localhost:27017') # this is default host
```

**Comment by Pechi77** [comment]
is there any documentation to connect mlab db?

**Comment by rianrajagede** [comment]
I'm sorry, I'm not a Mlab user, but I see there are nice explanations which you can see at [the official documentation here](https://docs.mlab.com/connecting/#connect-string)
